// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart'; // Ensure this file exists and contains Firebase configuration

Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLfVnpBHaw4i4lHCaZ5lkBxePKmN38_-w',
    appId: '1:376491874801:web:7293d3143a80bd919c4c50',
    messagingSenderId: '376491874801',
    projectId: 'notification-2bc24',
    authDomain: 'notification-2bc24.firebaseapp.com',
    storageBucket: 'notification-2bc24.firebasestorage.app',
    measurementId: 'G-SFLHXHZD1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnQMV6bb-6tiKIsNceo5gWWeGxqepxf3M',
    appId: '1:376491874801:android:752a1fd9d4c6facd9c4c50',
    messagingSenderId: '376491874801',
    projectId: 'notification-2bc24',
    storageBucket: 'notification-2bc24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbLrGzziDpe8E5jN2hcOMX-UkxhH5iWc4',
    appId: '1:376491874801:ios:d1f95afcefb13d879c4c50',
    messagingSenderId: '376491874801',
    projectId: 'notification-2bc24',
    storageBucket: 'notification-2bc24.firebasestorage.app',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbLrGzziDpe8E5jN2hcOMX-UkxhH5iWc4',
    appId: '1:376491874801:ios:d1f95afcefb13d879c4c50',
    messagingSenderId: '376491874801',
    projectId: 'notification-2bc24',
    storageBucket: 'notification-2bc24.firebasestorage.app',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLfVnpBHaw4i4lHCaZ5lkBxePKmN38_-w',
    appId: '1:376491874801:web:1063841cf2bfa4899c4c50',
    messagingSenderId: '376491874801',
    projectId: 'notification-2bc24',
    authDomain: 'notification-2bc24.firebaseapp.com',
    storageBucket: 'notification-2bc24.firebasestorage.app',
    measurementId: 'G-QC4XNB60NQ',
  );

}